; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp12e_ota

[env]
platform = espressif32
board = upesy_wroom
framework = arduino
lib_deps = 
	GyverLibs/Settings
	milesburton/DallasTemperature@^4.0.4
	256dpi/MQTT@^2.5.2
	thingsboard/TBPubSubClient@^2.12.1
monitor_speed = 57600
build_flags =
	-D OTA_DEFAULT_PASSWORD=\"8764956\"
; OTA uses ota_pass from NVS or OTA_DEFAULT_PASSWORD fallback.

[env:esp12e]
monitor_port = COM20
upload_protocol = esptool
upload_port = COM20

[env:esp12e_ota]
upload_protocol = espota
upload_port = 192.168.0.132
upload_flags =
	--port=8266
	--auth=8764956

; Первичная прошивка: python -m platformio run -e esp12e -t upload
; Последующие OTA: python -m platformio run -e esp12e_ota -t upload